/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface AppStencilStoreTodos {
    }
    interface AppTodos {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppStencilStoreTodosElement extends Components.AppStencilStoreTodos, HTMLStencilElement {
    }
    var HTMLAppStencilStoreTodosElement: {
        prototype: HTMLAppStencilStoreTodosElement;
        new (): HTMLAppStencilStoreTodosElement;
    };
    interface HTMLAppTodosElement extends Components.AppTodos, HTMLStencilElement {
    }
    var HTMLAppTodosElement: {
        prototype: HTMLAppTodosElement;
        new (): HTMLAppTodosElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "app-stencil-store-todos": HTMLAppStencilStoreTodosElement;
        "app-todos": HTMLAppTodosElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AppStencilStoreTodos {
    }
    interface AppTodos {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "app-stencil-store-todos": AppStencilStoreTodos;
        "app-todos": AppTodos;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-stencil-store-todos": LocalJSX.AppStencilStoreTodos & JSXBase.HTMLAttributes<HTMLAppStencilStoreTodosElement>;
            "app-todos": LocalJSX.AppTodos & JSXBase.HTMLAttributes<HTMLAppTodosElement>;
        }
    }
}
